=== skv11d/XML/xmlht2/task1/out/production/task1/stax/flowers.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Flower">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Plant" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="Soil" type="xs:string"/>
                            <xs:element name="Origin" type="xs:string"/>
                            <xs:element name="VisualParameters" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="StemColor" type="xs:string"/>
                                        <xs:element name="LeafColor" type="xs:string"/>
                                        <xs:element name="Size" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="GrowingTips" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Temperature" type="xs:string"/>
                                        <xs:element name="Lighting" type="xs:string"/>
                                        <xs:element name="Watering" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Multiplying" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== skv11d/XML/xmlht1/task2/src/flowers/flowers.xml
<?xml version="1.0" encoding="UTF-8"?>
<Flower xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="flowers.xsd">
    <Plant>
        <Name>Rose</Name>
        <Soil>Podzolic</Soil>
        <Origin>Europe</Origin>
        <VisualParameters>
            <StemColor>Red</StemColor>
            <LeafColor>Green</LeafColor>
            <Size>Medium</Size>
        </VisualParameters>
        <GrowingTips>
            <Temperature>20</Temperature>
            <Lighting>Sunlight</Lighting>
            <Watering>250</Watering>
        </GrowingTips>
        <Multiplying>Cuttings</Multiplying>
    </Plant>
    <Plant>
        <Name>Orchid</Name>
        <Soil>Ground</Soil>
        <Origin>Tropical regions</Origin>
        <VisualParameters>
            <StemColor>Green</StemColor>
            <LeafColor>Purple</LeafColor>
            <Size>Small</Size>
        </VisualParameters>
        <GrowingTips>
            <Temperature>25</Temperature>
            <Lighting>Shade</Lighting>
            <Watering>100</Watering>
        </GrowingTips>
        <Multiplying>Seeds</Multiplying>
    </Plant>
    <Plant>
        <Name>Cactus</Name>
        <Soil>Sandy</Soil>
        <Origin>America</Origin>
        <VisualParameters>
            <StemColor>Green</StemColor>
            <LeafColor>Green</LeafColor>
            <Size>Small</Size>
        </VisualParameters>
        <GrowingTips>
            <Temperature>30</Temperature>
            <Lighting>Sunlight</Lighting>
            <Watering>50</Watering>
        </GrowingTips>
        <Multiplying>Cuttings</Multiplying>
    </Plant>
    <Plant>
        <Name>Fern</Name>
        <Soil>Sod-podzolic</Soil>
        <Origin>Tropical and subtropical regions</Origin>
        <VisualParameters>
            <StemColor>Green</StemColor>
            <LeafColor>Green</LeafColor>
            <Size>Medium</Size>
        </VisualParameters>
        <GrowingTips>
            <Temperature>22</Temperature>
            <Lighting>Shade</Lighting>
            <Watering>200</Watering>
        </GrowingTips>
        <Multiplying>Spores</Multiplying>
    </Plant>
</Flower>
